// Well-known English Wikipedia articles used for "easy" picks and the daily
// challenge. Other languages get these translated through interlanguage links.
module.exports = [
  'Albert Einstein', 'Isaac Newton', 'Charles Darwin', 'Marie Curie', 'Leonardo da Vinci',
  'William Shakespeare', 'Napoleon', 'Julius Caesar', 'Cleopatra', 'Genghis Khan',
  'Abraham Lincoln', 'Winston Churchill', 'Mahatma Gandhi', 'Nelson Mandela', 'Queen Victoria',
  'Alexander the Great', 'Aristotle', 'Plato', 'Socrates', 'Confucius',
  'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Johann Sebastian Bach', 'The Beatles', 'Elvis Presley',
  'Michael Jackson', 'Taylor Swift', 'Pablo Picasso', 'Vincent van Gogh', 'Michelangelo',
  'Mona Lisa', 'Eiffel Tower', 'Great Wall of China', 'Colosseum', 'Taj Mahal',
  'Statue of Liberty', 'Stonehenge', 'Great Pyramid of Giza', 'Machu Picchu', 'Mount Everest',
  'Amazon River', 'Nile', 'Sahara', 'Pacific Ocean', 'Antarctica',
  'Moon', 'Sun', 'Mars', 'Jupiter', 'Saturn',
  'Milky Way', 'Black hole', 'Big Bang', 'Solar System', 'Earth',
  'Volcano', 'Earthquake', 'Tornado', 'Rainbow', 'Lightning',
  'Photosynthesis', 'DNA', 'Evolution', 'Dinosaur', 'Tyrannosaurus',
  'Cat', 'Dog', 'Horse', 'Elephant', 'Lion',
  'Tiger', 'Giant panda', 'Penguin', 'Shark', 'Octopus',
  'Honey bee', 'Butterfly', 'Eagle', 'Whale', 'Kangaroo',
  'Oak', 'Rose', 'Banana', 'Apple', 'Coffee',
  'Tea', 'Chocolate', 'Pizza', 'Sushi', 'Bread',
  'Cheese', 'Wine', 'Beer', 'Rice', 'Potato',
  'Football', 'Basketball', 'Baseball', 'Tennis', 'Cricket',
  'Chess', 'Olympic Games', 'FIFA World Cup', 'Formula One', 'Golf',
  'Computer', 'Internet', 'Smartphone', 'Artificial intelligence', 'Video game',
  'Television', 'Radio', 'Telephone', 'Printing press', 'Steam engine',
  'Electricity', 'Airplane', 'Automobile', 'Bicycle', 'Train',
  'Rocket', 'Satellite', 'Apollo 11', 'International Space Station', 'Titanic',
  'World War I', 'World War II', 'Cold War', 'French Revolution', 'American Revolution',
  'Roman Empire', 'Ancient Egypt', 'Ancient Greece', 'Vikings', 'Middle Ages',
  'Renaissance', 'Industrial Revolution', 'Black Death', 'Silk Road', 'Aztecs',
  'United States', 'United Kingdom', 'France', 'Germany', 'Japan',
  'China', 'India', 'Brazil', 'Australia', 'Canada',
  'Egypt', 'Italy', 'Mexico', 'Russia', 'South Africa',
  'London', 'Paris', 'New York City', 'Tokyo', 'Rome',
  'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Philosophy',
  'Democracy', 'Money', 'Language', 'Music', 'Film',
  'Harry Potter', 'Star Wars', 'The Lord of the Rings', 'Sherlock Holmes', 'Mickey Mouse',
  'Superman', 'Batman', 'Pokémon', 'Super Mario', 'Minecraft',
  'Christmas', 'Halloween', 'Pirate', 'Ninja', 'Samurai',
  'Knight', 'Castle', 'Dragon', 'Unicorn', 'Robot',
  'Gold', 'Diamond', 'Iron', 'Water', 'Fire',
  'Ice', 'Salt', 'Sugar', 'Oxygen', 'Carbon',
  'Human brain', 'Heart', 'Vaccine', 'Penicillin', 'Olive oil',
];